# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "answer.baml": "class Answer {\n  answer string\n}\n\nfunction AnswerQuestion(question: string, context: string, system_prompt: string) -> Answer {\n  client Anthropic\n  prompt #\"\n    {{ _.role(\"system\") }}\n    {{ system_prompt }}\n\n    Context:\n    {{ context }}\n\n    {{ _.role(\"user\") }}\n    {{ question }}\n  \"#\n}\n",
    "clients.baml": "client<llm> Anthropic {\n  provider anthropic\n  options {\n    model claude-sonnet-4-20250514\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n",
    "generator.baml": "generator target {\n  output_type \"python/pydantic\"\n  output_dir \"..\"\n  version \"0.220.0\"\n}\n",
}

def get_baml_files():
    return _file_map