# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "answer.baml": "enum MessageIntentKind {\n  SAVE_MEMORY\n  ANSWER_QUESTION\n}\n\nclass MessageIntent {\n  kind MessageIntentKind\n  memory_note string?\n  question string?\n}\n\nfunction ClassifyMessage(message: string) -> MessageIntent {\n  client Anthropic\n  prompt #\"\n    {{ _.role(\"system\") }}\n    Classify the user's message for an internal company knowledge assistant.\n\n    Use SAVE_MEMORY when the user wants the assistant to remember, save, note,\n    or record a durable fact for later.\n\n    Use ANSWER_QUESTION for greetings, questions, and all other normal chat.\n\n    If kind is SAVE_MEMORY, memory_note should contain the fact to save without\n    command phrasing like \"remember\" or \"save this\". Otherwise memory_note\n    should be null.\n\n    If kind is ANSWER_QUESTION, question should contain the user's message.\n    Otherwise question should be null.\n\n    {{ _.role(\"user\") }}\n    {{ message }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n\nfunction AnswerQuestion(question: string, context: string, system_prompt: string) -> string {\n  client Anthropic\n  prompt #\"\n    {{ _.role(\"system\") }}\n    {{ system_prompt }}\n\n    Context:\n    {{ context }}\n\n    {{ _.role(\"user\") }}\n    {{ question }}\n  \"#\n}\n",
    "clients.baml": "client<llm> Anthropic {\n  provider anthropic\n  options {\n    model claude-sonnet-4-20250514\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n",
    "generator.baml": "generator target {\n  output_type \"python/pydantic\"\n  output_dir \"..\"\n  version \"0.220.0\"\n}\n",
}

def get_baml_files():
    return _file_map